version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME_PREFIX}-apache-php"
    volumes:
      - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    container_name: "${CONTAINER_NAME_PREFIX}-mysql"
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  adminer:
    container_name: "${CONTAINER_NAME_PREFIX}-adminer"
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  db:

networks:
  app-network:
    driver: bridge